#%RAML 1.0
title: fuank-customer-api
version: v1
baseUri: http://faunk.dev.com/customer/api/{version}
protocols:
  [HTTPS,HTTP] 

documentation:
  - !include api_doc.raml

mediaType: 
- application/json

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

/customerDetails:
  is: [client-id-required]
  get:
    description: get Customer Data
    queryParameters:
      customerId: 
        type : string
        required: true
    displayName: get Customer Data
    responses: 
        200:
          body: 
            application/json:
              example: !include customer-example.json
        500:
          description: Something Went Wrong
          body:
            application/json:
              example: |
                {"message": "Somthing went wrong" }
  
  post:
    description: Create or update Customer Data 
    body:
      application/json:
        example: !include customer-example.json
    responses:
      201:
        description: Record created or updated sucessfully
        body:
          application/json:
            example: |
              { "message": "record updated successfully." }
      500:
        description: Something Went Wrong
        body:
          application/json:
            example: |
              {"message": "Somthing went wrong" }
  